name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  strategy:
  matrix:
    go-version: [1.17, 1.18, 1.19, 1.20]
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get -v -t ./...
      - name: Test
        run: go test -v ./...
      - name: Run
        run: go run math.go